#!/usr/bin/env bash

# qtile dir
qdir="$HOME/.config/qtile"

# Export desktop session
export XDG_CURRENT_DESKTOP='qtile'

# Kill already running process
_ps=(xsettingsd)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch xsettingsd daemon
xsettingsd --config="$qdir"/xsettingsd &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
hsetroot -cover "$qdir"/theme/wallpaper

# Lauch notification daemon
"$qdir"/scripts/qtile_dunst

# Lauch compositor
"$qdir"/scripts/qtile_comp

## Mount Google Drive
exec rclone mount --daemon GoogleDriveMain: ~/Google\ Drive &

## Launch JetBrains Toolbox
if ! pgrep -x jetbrains-toolbox >/dev/null; then
	exec jetbrains-toolbox --minimize &
fi

## Launch jamesdsp
exec jamesdsp -t &
