#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/qtile"
RASI="$DIR/theme/rofi/asroot.rasi"
ASROOT="$DIR/scripts/qtile_asroot"

# Theme Elements
prompt='Root'
mesg="Run Applications As Root"
term='kitty'

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
  option_1=" Kitty"
  option_2=" Nemo"
  option_3=" Yazi"
  option_4=" NeoVim"
else
  option_3=""
  option_2=""
  option_3=""
  option_4=""
  option_5=""
fi

# Rofi CMD
rofi_cmd() {
  rofi -dmenu \
    -p "$prompt" \
    -mesg "$mesg" \
    -markup-rows \
    -theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    ${ASROOT} "$term --session=none"
  elif [[ "$1" == '--opt2' ]]; then
    ${ASROOT} 'dbus-run-session nemo'
  elif [[ "$1" == '--opt3' ]]; then
    ${ASROOT} "$term yazi"
  elif [[ "$1" == '--opt4' ]]; then
    ${ASROOT} "$term nvim"
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
  run_cmd --opt1
  ;;
$option_2)
  run_cmd --opt2
  ;;
$option_3)
  run_cmd --opt3
  ;;
$option_4)
  run_cmd --opt4
  ;;
$option_5)
  run_cmd --opt5
  ;;
esac
